name: Tournaments

on:
  workflow_dispatch:
  schedule:
    - cron: "5/20 * * * *" # run every 30 minutes, starting at 5 past the hour

jobs:
  query:
    concurrency:
      group: scheduled-forecast-query
      cancel-in-progress: false
    permissions:
      actions: write
    outputs:
      post_ids: ${{ steps.post_ids.outputs.post_ids }}
    runs-on: ubuntu-latest
    steps:
      - id: post_ids
        run: |
          echo "post_ids=$(curl "https://www.metaculus.com/api/posts/?forecast_type=binary,discrete,multiple_choice,numeric&include_description=true&not_forecaster_id=$METACULUS_BOT_ID&offset=0&statuses=open&tournaments=fall-aib-2025&tournaments=minibench&tournaments=spring-aib-2026" -H "Authorization: Token $METACULUS_BOT_API_TOKEN" \
            | jq -c '.results | map(.id)')" >> $GITHUB_OUTPUT
        env:
          METACULUS_BOT_API_TOKEN: ${{ secrets.METACULUS_BOT_API_TOKEN }}
          METACULUS_BOT_ID: ${{ secrets.METACULUS_BOT_ID }}
      - if: steps.post_ids.outputs.post_ids == '' || steps.post_ids.outputs.post_ids == '[]'
        run: |
          gh run delete ${{ github.run_id }} --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  enqueue:
    if: ${{ needs.query.outputs.post_ids != '' && needs.query.outputs.post_ids != '[]' }}
    needs: query
    strategy:
      fail-fast: false
      matrix:
        post_id: ${{ fromJSON(needs.query.outputs.post_ids) }}
    concurrency:
      group: ${{ github.workflow }}+enqueue+${{ matrix.post_id }}
      cancel-in-progress: false
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      ASKNEWS_API_KEY: ${{ secrets.ASKNEWS_API_KEY }}
      DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
      METACULUS_BOT_API_TOKEN: ${{ secrets.METACULUS_BOT_API_TOKEN }}
      METACULUS_BOT_ID: ${{ secrets.METACULUS_BOT_ID }}
      OPEN_ROUTER_API_KEY: ${{ secrets.OPEN_ROUTER_API_KEY }}
      PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
    uses: ./.github/workflows/forecast.yml
    with:
      post_id: ${{ matrix.post_id }}
